### ISSUE TITLE
当子类model进行save到数据库的时候，找不到子类中继承父类model的属性

### ISSUE THREAD

**Issue by jiangjihui** [zoowii/jpa-utils#2]
当一个子类model继承一个父类model，然后子类进行save()操作的时候，找不到子类中所继承父类的属性，插入数据发生错误。
这是由于：JPAUtils在保存数据获取model中每个字段属性进行insert的时候通过ModelMeta.getColumnMetas()方法获取，而该方法是通过Class.getDeclaredFields();方法获取其class的属性。因为getDeclaredFields()：获得某个类的所有声明的字段，即包括public、private和proteced，但是不包括父类的申明字段。所以导致父类的属性获取不到。
解决方法可以看这篇博文：https://blog.csdn.net/qq_32452623/article/details/54025185

**Comment by zoowii** [comment]
目前就是这么设计的，只取本类定义的字段，将数据库表和一个model类一一对应，维护结构时不需要去考虑是否有父类中定义了本表的数据库字段。目前如果有少量重复字段可以复制粘贴。如果重复字段较多，需要继承父类字段的需求比较强烈我再考虑加上可选的继承父类字段的功能。

**Comment by jiangjihui** [comment]
谢谢解答
