### ISSUE TITLE
当Model类的主设置为Integer类型，主键生成策略为AUTO自增时，进行save保存会抛出：Long无法转换为Integer的异常

### ISSUE THREAD

**Issue by jiangjihui** [zoowii/jpa-utils#3]
Model类的主键为Integer类型，主键生成策略为
`@GeneratedValue(strategy = GenerationType.AUTO, generator = "idGenerator")
@TableGenerator(name = "idGenerator", allocationSize = 1)`

在对这个model进行save操作时，数据库自动生成的主键类型为long类型（Mysql的jar产生该主键），导致在设置到变量属性里面的时候无法转换。JdbcSession.save()方法获取到的generatedId字段为long型，导致在调用下面的idAccessor.setProperty(entity, generatedId);方法时出现类型转换异常。
如果把Model的主键类型改为Long型则不会出现上述问题，可以正常保存。

**Comment by zoowii** [comment]
先将主键设置为Long吧。Integer作为数据库主键能表达的范围太小了。这个BUG我之后会修复

**Comment by zoowii** [comment]
修改了一个版本，这个使用 idAccessor.setProperty的地方替换为了 idAccessor.setPropertyWithAutoTypeCast

新的库版本号为 1.9.21u13

**Comment by jiangjihui** [comment]
非常感谢😁
