### ISSUE TITLE
使用Expr.createIN()条件进行查找的时候，如果传入的是List<String>对象，会被多次拼接单引号的问题

### ISSUE THREAD

**Issue by jiangjihui** [zoowii/jpa-utils#4]
在使用Paginator类添加Expr.createIN()条件进行查找的时候，如果传入的是List<String>对象，里面的string会被2次赋予'(单引号)，推测应该是由于分页组件在进行分页查询的(ExtendFinder.java)时候第一次query.count()查询总数拼装了一次sql，接着调用query.all()方法在查询数据的时候又拼装了一次sql，两次拼装sql用的是同一个query对象，导致query里面的condition属性被多次修改（拼接sql）。所以在生成sql的时候会出现 in (''a'',''b'')这样的语句导致报错。
![image](https://user-images.githubusercontent.com/18020779/40780223-360f4abc-650a-11e8-9ce9-edaf540bb6d4.png)

![image](https://user-images.githubusercontent.com/18020779/40780118-ea86a626-6509-11e8-91da-5809cf465aa9.png)
目前是通过在传入值前自己拼接好单引号之后直接传入string对象而不是List对象来避免这个问题

**Comment by zoowii** [comment]
已修复，版本更新为1.9.21u14
